dist: xenial
cache:
  directories:
    - $HOME/.cache/pip

language: python

jobs:
  include:
    - stage: lint
      script: tox -e flake8
    - stage: test
      python: "2.6"
      env: TOXENV=py26
      dist: trusty
    - stage: test
      python: "2.7"
      env: TOXENV=py27
    - stage: test
      python: "2.7"
      env: TOXENV=py27-nooptionals
    - stage: test
      python: "3.4"
      env: TOXENV=py34
    - stage: test
      python: "3.5"
      env: TOXENV=py35
    - stage: test
      python: "3.6"
      env: TOXENV=py36
    - stage: test
      python: "3.7"
      env: TOXENV=py37
    - stage: test
      python: "3.8"
      env: TOXENV=py38
    - stage: test
      python: "3.8"
      env: TOXENV=py38-nooptionals
    - stage: test
      python: "pypy"
      env: TOXENV=pypy
    - stage: test
      python: "pypy3"
      env: TOXENV=pypy3

install:
  - pip install tox

script:
  - tox

notifications:
  email: false
